version: '3.1'
services:
  springapp:
    image: chydinma/spring-boot-mongo:2
    container_name: app_main2
    restart: always
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8010:8080
    depends_on:
      - mongo
    networks:
    - alpha
  mongo:
    image: mongo
    container_name: app_mongo2
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
      - ebs17:/data/db
    networks:
    - alpha
    ports:
      - 27017:27017
volumes:
  ebs17:
    external: true

networks:
  alpha:
    external: true
